<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function ByIndexArticles(){
    
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.visible = 1')
            ->andWhere('u.softDelete = 0')
            ->setMaxResults(4)
            ->orderBy('u.id', 'DESC');
        return $qb->getQuery()->getResult();
            
    }



    public function BySimilarArticle($id, $catalogue){
    
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.catalogue = :catalogue' )
            ->andWhere('u.visible = 1')
            ->andWhere('u.softDelete = 0')
            ->andWhere('u.id != :id')
            ->setMaxResults(3)
            ->orderBy('u.id', 'DESC')
            ->setParameter('catalogue',$catalogue)
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
            
    }
    public function ByRecentArticles(){
        $qb = $this->createQueryBuilder('u')
        ->select('u')
        ->where('u.visible = 1')
        ->andWhere('u.softDelete = 0')
        ->setMaxResults(4)
        ->orderBy('u.id', 'DESC');
    return $qb->getQuery()->getResult();
    }
}
