<?php

namespace AppBundle\Repository;

/**
 * BlogReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogReviewRepository extends \Doctrine\ORM\EntityRepository
{

}
