<?php

namespace AppBundle\Repository;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends \Doctrine\ORM\EntityRepository
{
    public function ByIndexContributions(){
    
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->setMaxResults(4)
            ->orderBy('u.id', 'DESC');
        return $qb->getQuery()->getResult();
            
    }


}
