<?php

namespace AppBundle\Repository;

/**
 * EmailCatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailCatchRepository extends \Doctrine\ORM\EntityRepository
{


}
