<?php

namespace AppBundle\Repository;

/**
 * EventCatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCatchRepository extends \Doctrine\ORM\EntityRepository
{


}
