<?php

namespace AppBundle\Repository;

/**
 * EventEmailCatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventEmailCatchRepository extends \Doctrine\ORM\EntityRepository
{


}
