<?php

namespace AppBundle\Repository;

/**
 * VolonteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolonteerRepository extends \Doctrine\ORM\EntityRepository
{

}
