<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerStlpqp6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerStlpqp6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerStlpqp6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerStlpqp6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerStlpqp6\appProdProjectContainer([
    'container.build_hash' => 'Stlpqp6',
    'container.build_id' => '0c2d1c59',
    'container.build_time' => 1600994684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerStlpqp6');
