<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEmqhehj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEmqhehj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEmqhehj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEmqhehj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEmqhehj\appDevDebugProjectContainer([
    'container.build_hash' => 'Emqhehj',
    'container.build_id' => '2b17f30b',
    'container.build_time' => 1605875929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEmqhehj');
