<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvrfbyy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvrfbyy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHvrfbyy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHvrfbyy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHvrfbyy\appDevDebugProjectContainer([
    'container.build_hash' => 'Hvrfbyy',
    'container.build_id' => '44f17fb6',
    'container.build_time' => 1606915168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvrfbyy');
